name: podium
version: 1.2.5+155
publish_to: none
description: web3 Podium.
environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  # State Management & Routing
  get: ^5.0.0-release-candidate-9.3.2
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  get_storage: ^2.1.1

  # UI Components & Animations
  visibility_detector: ^0.4.0+2
  flutter_slidable: ^4.0.0
  shimmer: ^3.0.0
  skeletonizer: ^1.4.3
  flutter_confetti: ^0.5.1
  floating_draggable_widget: ^2.3.0
  dropdown_button2: ^2.3.9
  auto_size_text: ^3.0.0
  getwidget: ^6.0.0
  pulsator: ^1.0.0+2
  rotated_corner_decoration: ^2.1.0
  glow_container: ^1.0.1
  auto_animated: ^3.2.0
  flutter_spinkit: ^5.2.1
  marquee: ^2.3.0
  tutorial_coach_mark: ^1.2.13
  animated_icon: ^0.0.9

  # Audio & Media
  just_audio: ^0.9.46
  just_waveform: ^0.0.7
  record: ^6.0.0
  flutter_sound: ^9.28.0
  siri_wave: ^2.3.0

  # Storage & File Management
  path_provider: ^2.1.5
  downloadsfolder: ^1.2.0
  firebase_storage: ^12.4.5
  cached_network_image: ^3.4.1

  # Firebase Services
  firebase_core: ^3.13.0
  firebase_analytics: ^11.4.5
  firebase_auth: ^5.5.2

  # Forms & Input
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  image_picker: ^1.1.2
  textfield_tags: ^3.0.1

  # Web3 & Blockchain
  web3auth_flutter: ^5.0.4
  web3dart: ^2.7.3
  aptos:
    git:
      url: https://github.com/mhsnprvr/aptos.git
      ref: developing
  ed25519_edwards: ^0.3.1
  eth_sig_util: ^0.0.9

  # Networking & API
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  web_socket_channel: ^3.0.2
  internet_connection_checker_plus: ^2.7.1

  # Utilities
  dartx: ^1.2.0
  decimal: ^3.2.1
  uuid: ^4.5.1
  logger: ^2.5.0
  gap: ^3.0.1
  json_annotation: ^4.9.0
  copy_with_extension_gen: ^6.0.1
  enhanced_paginated_view: ^2.0.3

  # Device Features & Permissions
  alarm: ^5.1.0
  permission_handler: ^12.0.0
  app_settings: ^6.1.1
  onesignal_flutter: ^5.3.0

  # Environment & Configuration
  flutter_dotenv: ^5.2.1
  reown_appkit: ^1.4.2

  # Sharing & Links
  share_plus: ^10.1.4
  app_links: ^6.4.0
  url_launcher: ^6.3.1
  add_2_calendar: ^3.0.1

  # Video Conferencing
  jitsi_meet_flutter_sdk:
    path: ./jitsi-meet-flutter-sdk

  # Code Quality
  lint: ^2.3.0

  flutter:
    sdk: flutter

dependency_overrides:
  intl: ^0.19.0

dev_dependencies:
  device_preview: ^1.2.0
  flutter_native_splash: ^2.4.6
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  icons_launcher: ^3.0.1
  json_serializable: ^6.9.4
  change_app_package_name: ^1.5.0

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  colors:
    inputs:
      - assets/colors/colors.xml
  # Optional
  integrations:
    flutter_svg: true
    rive: true
    lottie: true

flutter:
  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Light.ttf
          weight: 400
        - asset: assets/fonts/Sora-Regular.ttf
          weight: 500
        - asset: assets/fonts/Sora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Sora-Bold.ttf
          weight: 700
  assets:
    - assets/images/
    - assets/audio/blip.mp3
    - env/production.env
    - env/development.env
  uses-material-design: true
