name: podium
version: 1.0.4+33
publish_to: none
description: web3 Podium.
environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  get: ^5.0.0-release-candidate-9.2
  flutter:
    sdk: flutter
  reown_appkit: ^1.0.1
  intl: ^0.19.0
  share_plus: ^10.0.2
  app_links: ^6.3.2
  fl_toast: ^3.2.0
  floating_draggable_widget: ^2.1.5
  dropdown_button2: ^2.3.9
  firebase_core: ^3.5.0
  firebase_database: ^11.1.3
  firebase_auth: ^5.3.0
  get_storage: ^2.1.1
  getwidget: ^4.0.0
  flutter_form_builder: ^9.4.1
  form_builder_validators: ^11.0.0
  image_picker: ^1.1.2
  firebase_storage: ^12.3.1
  uuid: ^4.5.0
  logger: ^2.4.0
  jitsi_meet_flutter_sdk:
    path: ./jitsi_plugin
  gap: ^3.0.1
  internet_connection_checker_plus: ^2.5.2
  cached_network_image: ^3.4.1
  permission_handler: ^11.3.1
  app_settings: ^5.1.1
  url_launcher: ^6.3.0
  particle_auth_core: ^2.1.3
  firebase_analytics: ^11.3.2

dependency_overrides:
  web: ^0.5.0
# dependency overrides

dev_dependencies:
  flutter_native_splash: ^2.4.1
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.7.0
  icons_launcher: ^3.0.0
  json_serializable: ^6.8.0
  change_app_package_name: ^1.3.0
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  colors:
    inputs:
      - assets/colors/colors.xml
  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Light.ttf
          weight: 400
        - asset: assets/fonts/Sora-Regular.ttf
          weight: 500
        - asset: assets/fonts/Sora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Sora-Bold.ttf
          weight: 700
  assets:
    - assets/images/
  uses-material-design: true
