name: podium
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  json_annotation: ^4.9.0
  get: ^4.6.5
  flutter:
    sdk: flutter
  walletconnect_flutter_v2: ^2.2.3
  web3modal_flutter: ^3.2.2
  intl: ^0.19.0
  fl_toast: ^3.2.0
  firebase_core: ^3.2.0
  firebase_database: ^11.0.3
  firebase_auth: ^5.1.2
  get_storage: ^2.1.1
  getwidget: ^4.0.0
  flutter_form_builder: ^9.3.0
  form_builder_validators: ^11.0.0
  image_picker: ^1.1.2
  firebase_storage: ^12.1.1
  firebase_app_check: ^0.3.0+3
  uuid: ^4.4.2
  floating_draggable_widget: ^2.1.5
  logger: ^2.4.0
  jitsi_meet_flutter_sdk: ^0.4.2
  flutter_native_splash: ^2.4.1
  google_fonts: ^6.2.1
  gap: ^3.0.1
  flutter_staggered_animations: ^1.1.1
  cloud_firestore: ^5.1.0
  rxdart: ^0.28.0
  internet_connection_checker_plus: ^2.5.0
  particle_auth: ^1.4.28

dev_dependencies:
  build_runner: ^2.4.11
  flutter_gen_runner: 5.6.0
  flutter_lints: ^3.0.0
  icons_launcher: ^2.1.7
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  colors:
    inputs:
      - assets/colors/colors.xml
  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Light.ttf
          weight: 400
        - asset: assets/fonts/Sora-Regular.ttf
          weight: 500
        - asset: assets/fonts/Sora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Sora-Bold.ttf
          weight: 700
  assets:
    - assets/images/
  uses-material-design: true
