// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCB1GlqH8o8pgY7L9n9YtppB4-2ZoyKII',
    appId: '1:891834977013:web:2d5970af9607331c4593bc',
    messagingSenderId: '891834977013',
    projectId: 'podium-fbb5b',
    authDomain: 'podium-fbb5b.firebaseapp.com',
    databaseURL: 'https://podium-fbb5b-default-rtdb.firebaseio.com',
    storageBucket: 'podium-fbb5b.appspot.com',
    measurementId: 'G-4VGY187123',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUa5XtcdM73jMYLSO4Wg7tRvChmbMbqNg',
    appId: '1:891834977013:android:813d7243ba4456a14593bc',
    messagingSenderId: '891834977013',
    projectId: 'podium-fbb5b',
    databaseURL: 'https://podium-fbb5b-default-rtdb.firebaseio.com',
    storageBucket: 'podium-fbb5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2w1ipnCMXQ7NI3curHqX8nEXu3M0ZVnU',
    appId: '1:891834977013:ios:49bfd025b32891194593bc',
    messagingSenderId: '891834977013',
    projectId: 'podium-fbb5b',
    databaseURL: 'https://podium-fbb5b-default-rtdb.firebaseio.com',
    storageBucket: 'podium-fbb5b.appspot.com',
    iosBundleId: 'com.movement.podium',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2w1ipnCMXQ7NI3curHqX8nEXu3M0ZVnU',
    appId: '1:891834977013:ios:49bfd025b32891194593bc',
    messagingSenderId: '891834977013',
    projectId: 'podium-fbb5b',
    databaseURL: 'https://podium-fbb5b-default-rtdb.firebaseio.com',
    storageBucket: 'podium-fbb5b.appspot.com',
    iosBundleId: 'com.movement.podium',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCB1GlqH8o8pgY7L9n9YtppB4-2ZoyKII',
    appId: '1:891834977013:web:ab3afebf29dfd7f74593bc',
    messagingSenderId: '891834977013',
    projectId: 'podium-fbb5b',
    authDomain: 'podium-fbb5b.firebaseapp.com',
    databaseURL: 'https://podium-fbb5b-default-rtdb.firebaseio.com',
    storageBucket: 'podium-fbb5b.appspot.com',
    measurementId: 'G-WDSWJMYZTX',
  );

}